apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hm-admin-ingress
  annotations:
    # 1. Ingress Controller 지정
    kubernetes.io/ingress.class: traefik

    # 2. Cert-Manager에게 인증서를 발급 요청하는 어노테이션 추가 (필수)
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
    - hosts:
        - hm-admin-dev.dog-foot.com
      secretName: hm-admin-dev-tls
  rules:
    - host: hm-admin-dev.dog-foot.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: hm-admin-svc
                port:
                  number: 80
